# Generated by Django 5.2.6 on 2025-09-16 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('football shoes', 'Football Shoes'), ('training gear', 'Training Gear'), ('training jacket', 'Training Jacket'), ('accessories', 'Accessories'), ('equipments', 'Equipments')], default='Jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('product_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
