# Generated by Django 5.2.5 on 2025-10-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('football shoes', 'Football Shoes'), ('training gear', 'Training Gear'), ('training jacket', 'Training Jacket'), ('accessories', 'Accessories'), ('equipments', 'Equipments')], default='jersey', max_length=20),
        ),
    ]
